name: Test and Lint

on:
  pull_request:
    branches:
      - dev

env:
  DATABASE_URL: "sqlite:///./db.sqlite"
  PASSWORD_RESET_LINK: "127.0.0.1" 
  ACTIVATE_ACCOUNT_LINK: "127.0.0.1:8000"
  JWT_VALID_TIME_ACCESS: 1200 
  JWT_VALID_TIME_REFRESH: 604800
  JWT_VALID_TIME_PWD_RESET: 600 
  JWT_VALID_TIME_ACTIVATE_ACCOUNT: 1800
  JWT_SECRET: "secret"
  JWT_ALGORITHM: "HS256"
  MAIL_USERNAME: "kosjenka.readingapp@gmail.com"
  MAIL_PASSWORD: "${{ secrets.MAIL_PASSWORD }}"
  MAIL_PORT: 587
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_FROM_NAME: "Kosjenka Support"
  SUPERADMIN_LOGIN: "superadmin@gmail.com"
  SUPERADMIN_PASSWORD: "superadmin"


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python3 -m pytest

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check --diff"
